# -*- coding: utf-8 -*-
"""MIN GPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ham-OsoVZOI4E1KKKUrRVXiAdU2D4DW6
"""

pip install torch

pip install einops

pip install tokenizers

## Utils File

import os
import sys
import json
import random
from ast import literal_eval
import torch
from torch import nn
from torch.nn import functional as F
from einops import einsum, rearrange
import numpy as np

def set_seed(seed: int):
    """
    Sets the seed for reproducibility across different libraries.

    Args:
        seed (int): The integer seed to use for random number generation.
    """
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

def setup_logging(config):
    """ monotonous bookkeeping, logging the system output """
    work_dir = config.system.work_dir
    # create the work directory if it doesn't already exist
    os.makedirs(work_dir, exist_ok=True)
    # log the args (if any)
    with open(os.path.join(work_dir, 'args.txt'), 'w') as f:
        f.write(' '.join(sys.argv))
    # log the config itself
    with open(os.path.join(work_dir, 'config.json'), 'w') as f:
        f.write(json.dumps(config.to_dict(), indent=4))

class CfgNode:
    """ a lightweight configuration class inspired by yacs """

    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)

    def __str__(self):
        return self._str_helper(0)

    def _str_helper(self, indent):
        """ need to have a helper to support nested indentation for pretty printing """
        parts = []
        for k, v in self.__dict__.items():
            if isinstance(v, CfgNode):
                parts.append("%s:\n" % k)
                parts.append(v._str_helper(indent + 1))
            else:
                parts.append("%s: %s\n" % (k, v))
        parts = [' ' * (indent * 4) + p for p in parts]
        return "".join(parts)

    def to_dict(self):
        """ return a dict representation of the config """
        return { k: v.to_dict() if isinstance(v, CfgNode) else v for k, v in self.__dict__.items() }

    def merge_from_dict(self, d):
        self.__dict__.update(d)

    def merge_from_args(self, args):
        """
        update the configuration from a list of strings that is expected
        to come from the command line, i.e. sys.argv[1:].

        The arguments are expected to be in the form of `--arg=value`, and
        the arg can use . to denote nested sub-attributes. Example:

        --model.n_layer=10 --trainer.batch_size=32
        """
        for arg in args:

            keyval = arg.split('=')
            assert len(keyval) == 2, "expecting each override arg to be of form --arg=value, got %s" % arg
            key, val = keyval # unpack

            # first translate val into a python object
            try:
                val = literal_eval(val)
                """
                need some explanation here.
                - if val is simply a string, literal_eval will throw a ValueError
                - if val represents a thing (like an 3, 3.14, [1,2,3], False, None, etc.) it will get created
                """
            except ValueError:
                pass

            # find the appropriate object to insert the attribute into
            assert key[:2] == '--'
            key = key[2:] # strip the '--'
            keys = key.split('.')
            obj = self
            for k in keys[:-1]:
                obj = getattr(obj, k)
            leaf_key = keys[-1]

            # ensure that this attribute exists
            assert hasattr(obj, leaf_key), f"{key} is not an attribute that exists in the config"

            # overwrite the attribute
            print("command line overwriting config attribute %s with %s" % (key, val))
            setattr(obj, leaf_key, val)

# Commented out IPython magic to ensure Python compatibility.
import math
import torch
from torch import nn
from torch.nn import functional as F
from einops import einsum, rearrange
import json
import time
import os

class NewGELU(nn.Module):
  def forward(self, x):
    return 0.5 * x * (1.0 + torch.tanh(math.sqrt(2.0 / math.pi) * (x + 0.044715 * torch.pow(x, 3.0))))

class RotaryPositionalEmbedding(nn.Module):
  def __init__(self, d: int, base: int = 10000):
    super().__init__()
    self.d = d

    inv_frequency = 1.0/(base**(torch.arange(0,d,2).float()/d)) ## The theta values will be equal to 10000^(2i/d). We use d/2 because we will be following pair-wise rotation of dimensions
    self.register_buffer("inv_frequency",inv_frequency)

    self.cos_cached = None
    self.sin_cached = None

  def _build_cache(self, x: torch.Tensor):
    """
    Builds a cache for cos and sin values based on the sequence length of x.
    x shape: [batch, seq_len, num_heads, head_dim] or [batch, seq_len, head_dim]
    """
    seq_len = x.shape[1]

    # Only rebuild cache if sequence length increases or cache is empty
    if self.cos_cached is None or seq_len > self.cos_cached.shape[1]:
    # Create position indices [0, 1, ..., seq_len-1]
      t = torch.arange(seq_len, device=x.device).type_as(self.inv_frequency)

      # Outer product to get matrix of (pos * theta)
      # freqs shape: [seq_len, d/2]
      freqs = torch.einsum("i,j->ij", t, self.inv_frequency)

      # Repeat frequencies for the 'rotate half' trick: [cos(f1), cos(f2), cos(f1), cos(f2)]
      # emb shape: [seq_len, d]
      emb = torch.cat((freqs, freqs), dim=-1)

      # Cache shape: [1, seq_len, 1, d] to allow broadcasting across batch and heads
      self.cos_cached = emb.cos()[None, :, None, :]
      self.sin_cached = emb.sin()[None, :, None, :]

  @staticmethod
  def _rotate_half(x: torch.Tensor):
    x1, x2 = x[..., :x.shape[-1]//2], x[..., x.shape[-1]//2:]
    return torch.cat((-x2, x1), dim=-1)

  def forward(self, x: torch.Tensor):
    if self.cos_cached is None:
      self._build_cache(x)
    seq_len = x.shape[1]
    cos = self.cos_cached[:, :seq_len, :, :].to(x.device)
    sin = self.sin_cached[:, :seq_len, :, :].to(x.device)

    return (x * cos) + (RotaryPositionalEmbedding._rotate_half(x) * sin)

class CausalSelfAttention(nn.Module):
  def __init__(self, config):
    super().__init__()
    assert config.n_embd % config.n_head == 0 ## This line of the code will check dimensions (example 768 or 512) and compare it with number of heads to ensure there is no embeddings left out

    self.n_head = config.n_query_head
    self.n_embd = config.n_embd

    # key, query, value projections for all heads, but in a batch
    self.q_proj = nn.Linear(config.n_embd, config.n_embd)
    self.k_proj = nn.Linear(config.n_embd, config.n_embd)
    self.v_proj = nn.Linear(config.n_embd, config.n_embd)

    # Output projection
    self.out_proj = nn.Linear(config.n_embd, config.n_embd)

    #Regularization
    self.attn_dropout = nn.Dropout(config.attn_pdrop)
    self.resid_dropout = nn.Dropout(config.resid_pdrop)

    #Causal Mask which is applied to ensure that attention is applied only on the left side of the network
    self.register_buffer("bias", torch.tril(torch.ones(config.block_size, config.block_size)).view(1, 1, config.block_size, config.block_size))

    self.rope = config.rope
    if self.rope:
      self.rotary_emb = RotaryPositionalEmbedding(config.n_embd)

  def forward(self, x):
    b, t, n_embd = x.size() # Batch size, Sequence_length and Embedding Dimensionality

    # Calculating the query, Key and Value based on X
    q = self.q_proj(x) # (b, t, n_embd)
    k = self.k_proj(x) # (b, t, n_embd)
    v = self.v_proj(x) # (b, t, n_embd)

    #split the embedding dimension (n_embd) across the number of heads by introducing an additional 'h' dimension
    # reshape the query, key, value tensors to increase efficacy of matrix multiplication
    # b=batch size, t=sequence length, h= number of heads, d = n_embd/heads
    q=rearrange(q, 'b t (h d) -> b h t d', h=self.n_head)
    k=rearrange(k, 'b t (h d) -> b h t d', h=self.n_head)
    v=rearrange(v, 'b t (h d) -> b h t d', h=self.n_head)

    if self.rope:
      q = self.rotary_emb(q)
      k = self.rotary_emb(k)

    #track the memory used by the model
    torch.cuda.empty_cache()
    start_memory = torch.cuda.memory_allocated()

    #compute the square root of (n_embd/ number of heads) to scale the dot product

    scale = math.sqrt(k.size(-1))

    #Calculate the attention scores with the query and Key
    att = einsum(q, k, 'b h q d, b h k d -> b h q k') / scale
    att = att.masked_fill(self.bias[:,:,:t,:t] == 0, float('-inf'))
    att = F.softmax(att, dim=-1)
    att = self.attn_dropout(att)

    # Matrix multiplication of Attention scores and value
    y=einsum(att, v, 'b h q t, b h t d -> b h q d')
    end_memory = torch.cuda.memory_allocated()

    # Rearrange the output tensor to (batch size, sequence length and n_embd)

    y = rearrange(y, 'b h q d -> b q (h d)')

    #output projection
    y = self.resid_dropout(self.out_proj(y))
    return y, end_memory - start_memory

class GroupedQueryAttention(nn.Module):
  def __init__(self, config):
    super().__init__()
    assert config.n_embd % config.n_head == 0 # The embedding dimension is divisible by the number of query heads and key-value heads.
    self.n_head = config.n_query_head
    self.n_kv_head = config.n_kv_head  # New parameter (e.g., 8 if n_head is 32)
    self.head_dim = config.n_embd // self.n_head
    self.n_groups = self.n_head // self.n_kv_head

    # Query, Key & Value for all heads but in a batch
    self.q_proj = nn.Linear(config.n_embd, config.n_embd)
    #K & V project into a smaller subspace for GQA
    self.k_proj = nn.Linear(config.n_embd, self.n_kv_head * self.head_dim)
    self.v_proj = nn.Linear(config.n_embd, self.n_kv_head * self.head_dim)

    # Output projection
    self.out_proj = nn.Linear(config.n_embd, config.n_embd)

    # Regularization
    self.attn_dropout = nn.Dropout(config.attn_pdrop)
    self.resid_dropout = nn.Dropout(config.resid_pdrop)

    #Causal Mask which is applied to ensure that attention is applied only on the left side of the network
    self.register_buffer("bias", torch.tril(torch.ones(config.block_size, config.block_size)).view(1, 1, config.block_size, config.block_size))

    self.rope = config.rope
    if self.rope:
      self.rotary_emb = RotaryPositionalEmbedding(config.n_embd)

  def forward(self, x):

    b, t, _ = x.size()

    q = self.q_proj(x) # (b, t, n_head * head_dim)
    k = self.k_proj(x) # (b, t, n_kv_head * head_dim)
    v = self.v_proj(x) # (b, t, n_kv_head * head_dim)

    # Reshape heads
    q = rearrange(q, 'b t (h d) -> b h t d', h=self.n_head)
    k = rearrange(k, 'b t (h d) -> b h t d', h=self.n_kv_head)
    v = rearrange(v, 'b t (h d) -> b h t d', h=self.n_kv_head)

    # NEW: Repeat K and V heads to match Q head count
    # This aligns the groups so einsum works correctly
    k = torch.repeat_interleave(k, self.n_groups, dim=1)
    v = torch.repeat_interleave(v, self.n_groups, dim=1)

    if self.rope:
        q = self.rotary_emb(q)
        k = self.rotary_emb(k)

    # Use PyTorch's optimized attention for better performance in 2026
    # This automatically handles causal masking and scaling
    y = F.scaled_dot_product_attention(
        q, k, v,
        attn_mask=None,
        dropout_p=self.attn_dropout.p if self.training else 0,
        is_causal=True
    )

    y = rearrange(y, 'b h t d -> b t (h d)')
    return self.resid_dropout(self.out_proj(y))

class Block (nn.Module):
  def __init__(self, config):
    super().__init__()
    self.ln_1 = nn.LayerNorm(config.n_embd)
    if config.n_query_head != config.n_kv_head:
      self.attn = GroupedQueryAttention(config)
    else:
      self.attn = CausalSelfAttention(config)
    self.ln_2 = nn.LayerNorm(config.n_embd)
    self.mlp = nn.ModuleDict(dict(
        c_fc = nn.Linear(config.n_embd, 4 * config.n_embd),
        c_proj = nn.Linear(4 * config.n_embd, config.n_embd),
        act = NewGELU(),
        dropout = nn.Dropout(config.resid_pdrop),
    ))
    m=self.mlp
    self.mlpf = lambda x: m.dropout(m.c_proj(m.act(m.c_fc(x)))) # MLP forward

  def forward(self, x):
    start_time = time.time()
    # Fixed typo: self.ln1 -> self.ln_1 and self.ln2 -> self.ln_2
    attn_comp, mem_consumed = self.attn(self.ln_1(x))
    end_time = time.time()
    x = x + attn_comp
    x = x + self.mlpf(self.ln_2(x))
    return x, end_time - start_time, mem_consumed

class GPT(nn.Module):
  @staticmethod
  def get_default_config():
    C = CfgNode() # Changed to CfgNode as defined earlier
    #Either the model type or (n_layer, n_head or n_config must be given in the code)
    C.model_type = 'gpt'
    C.n_layer = None
    C.n_head = None
    C.n_embd = None
    # These options must be externally inputted
    C.vocab_size = None # Changed from n_vocab to vocab_size for consistency
    C.block_size = None # Changed from n_ctx to block_size for consistency
    # Dropout Hyper Parameters
    C.embd_pdrop = 0.1
    C.resid_pdrop = 0.1
    C.attn_pdrop = 0.1
    C.pretrained_folder = None
    C.n_query_head = None # Added for clarity, as n_head is used for query heads
    C.n_kv_head = C.n_query_head
    return C

  def __init__(self, config):
    super().__init__()
    assert config.vocab_size is not None
    assert config.block_size is not None

    self.block_size = config.block_size
    self.rope = config.rope

    modules = dict(
        wte = nn.Embedding(config.vocab_size, config.n_embd),
        drop = nn.Dropout(config.embd_pdrop),
        h=nn.ModuleList([Block(config) for _ in range(config.n_layer)]),
        ln_f = nn.LayerNorm(config.n_embd)
    )
    if self.rope==False:
        modules['wpe'] = nn.Embedding(config.block_size, config.n_embd)
    self.transformer = nn.ModuleDict(modules)
    self.lm_head = nn.Linear(config.n_embd, config.vocab_size, bias=False)

    # init all weights, and apply a special scaled init to the residual projections, per GPT-2 paper
    self.apply(self._init_weights)
    for pn, p in self.named_parameters():
        if pn.endswith('c_proj.weight'):
            torch.nn.init.normal_(p, mean=0.0, std=0.02/math.sqrt(2 * config.n_layer))

    # report number of parameters (note we don't count the decoder parameters in lm_head)
    n_params = sum(p.numel() for p in self.transformer.parameters())
    print("number of parameters: %.2fM" % (n_params/1e6,))

  def _init_weights(self, module):
      if isinstance(module, nn.Linear):
          torch.nn.init.normal_(module.weight, mean=0.0, std=0.02);
          if module.bias is not None:
              torch.nn.init.zeros_(module.bias)
      elif isinstance(module, nn.Embedding):
          torch.nn.init.normal_(module.weight, mean=0.0, std=0.02);
      elif isinstance(module, nn.LayerNorm):
          torch.nn.init.zeros_(module.bias)
          torch.nn.init.ones_(module.weight)

  def load_pretrained(self, model_path):
      pretrained_state_dict = torch.load(os.path.join(model_path, "model.pt"))
      old_block_size = 64
      with open(os.path.join(model_path,'config.json'), 'r') as file:
          old_config = json.load(file)
          old_block_size = old_config['data']['block_size']
      # Initialize the current model state dict
      self_state_dict = self.state_dict()

      # Loop over the pretrained state dict and update the corresponding weights
      for name, param in pretrained_state_dict.items():
          if name in self_state_dict:
              # If it's the wpe layer and sizes are different, handle separately
              if name == 'transformer.wpe.weight' and param.size(0) != self_state_dict[name].size(0):
                  # Copy the weights for the first 64 neurons
                  self_state_dict[name][:old_block_size, :] = param[:old_block_size, :]
              elif name.startswith("transformer.h.") and name.endswith(".attn.bias") and param.size()[2] != self_state_dict[name].size()[2]:
                  self_state_dict[name][:,:,:old_block_size,:old_block_size] = param
                  # Remaining weights are already randomly initialized
              else:
                  # Copy the weights for layers other than wpe
                  self_state_dict[name].copy_(param)

      # Load the updated state dict into the model
      self.load_state_dict(self_state_dict)

  def configure_optimizers(self, train_config):
      """
      This long function is unfortunately doing something very simple and is being very defensive:
      We are separating out all parameters of the model into two buckets: those that will experience
      weight decay for regularization and those that won't (biases, and layernorm/embedding weights).
      We are then returning the PyTorch optimizer object.
      """

      # separate out all parameters to those that will and won't experience regularizing weight decay
      decay = set()
      no_decay = set()
      whitelist_weight_modules = (torch.nn.Linear, )
      blacklist_weight_modules = (torch.nn.LayerNorm, torch.nn.Embedding)
      for mn, m in self.named_modules():
          for pn, p in m.named_parameters():
              fpn = '%s.%s' % (mn, pn) if mn else pn # full param name
              # random note: because named_modules and named_parameters are recursive
              # we will see the same tensors p many many times. but doing it this way
              # allows us to know which parent module any tensor p belongs to...
              if pn.endswith('bias'):
                  # all biases will not be decayed
                  no_decay.add(fpn)
              elif pn.endswith('weight') and isinstance(m, whitelist_weight_modules):
                  # weights of whitelist modules will be weight decayed
                  decay.add(fpn)
              elif pn.endswith('weight') and isinstance(m, blacklist_weight_modules):
                  # weights of blacklist modules will NOT be weight decayed
                  no_decay.add(fpn)

      # validate that we considered every parameter
      param_dict = {pn: p for pn, p in self.named_parameters()}
      inter_params = decay & no_decay
      union_params = decay | no_decay
      assert len(inter_params) == 0, "parameters %s made it into both decay/no_decay sets!" % (str(inter_params), )
      assert len(param_dict.keys() - union_params) == 0, "parameters %s were not separated into either decay/no_decay set!" \
#                                                   % (str(param_dict.keys() - union_params), )

      # create the pytorch optimizer object
      optim_groups = [
          {"params": [param_dict[pn] for pn in sorted(list(decay))], "weight_decay": train_config.weight_decay},
          {"params": [param_dict[pn] for pn in sorted(list(no_decay))], "weight_decay": 0.0},
      ]
      optimizer = torch.optim.AdamW(optim_groups, lr=train_config.learning_rate, betas=train_config.betas)
      return optimizer

  def forward(self, idx, targets=None):
      attn_times = []
      mem_consumed = []
      device = idx.device
      b, t = idx.size()
      assert t <= self.block_size, f"Cannot forward sequence of length {t}, block size is only {self.block_size}"
      pos = torch.arange(0, t, dtype=torch.long, device=device).unsqueeze(0) # shape (1, t)

      # forward the GPT model itself
      tok_emb = self.transformer.wte(idx) # token embeddings of shape (b, t, n_embd)
      if self.rope==False:
          pos_emb = self.transformer.wpe(pos) # position embeddings of shape (1, t, n_embd)
          x = self.transformer.drop(tok_emb + pos_emb)
      else:
          x = self.transformer.drop(tok_emb)
      for block in self.transformer.h:
          x, attn_time, mem = block(x)
          mem_consumed.append(mem)
          attn_times.append(attn_time)
      x = self.transformer.ln_f(x)
      logits = self.lm_head(x)

      # if we are given some desired targets also calculate the loss
      loss = None
      if targets is not None:
          loss = F.cross_entropy(logits.view(-1, logits.size(-1)), targets.view(-1), ignore_index=-1)

      return logits, loss, sum(attn_times)/len(attn_times), sum(mem_consumed)/len(mem_consumed)

  @torch.no_grad()
  def generate(self, idx, max_new_tokens, temperature=1.0, do_sample=False, top_k=None, eos_token_id=None):
      """
      Take a conditioning sequence of indices idx (LongTensor of shape (b,t)) and complete
      the sequence max_new_tokens times, feeding the predictions back into the model each time.
      Most likely you'll want to make sure to be in model.eval() mode of operation for this.
      Added eos_token_id to stop generation early.
      """
      attn_times = []
      for _ in range(max_new_tokens):
          # if the sequence context is growing too long we must crop it at block_size
          idx_cond = idx if idx.size(1) <= self.block_size else idx[:, -self.block_size:]
          # forward the model to get the logits for the index in the sequence
          logits, _,attn_time,mem_consumed = self(idx_cond)
          # pluck the logits at the final step and scale by desired temperature
          logits = logits[:, -1, :] / temperature
          # optionally crop the logits to only the top k options
          if top_k is not None:
              v, _ = torch.topk(logits, top_k)
              logits[logits < v[:, [-1]]] = -float('Inf')
          # apply softmax to convert logits to (normalized) probabilities
          probs = F.softmax(logits, dim=-1)
          # either sample from the distribution or take the most likely element
          if do_sample:
              idx_next = torch.multinomial(probs, num_samples=1)
          else:
              _, idx_next = torch.topk(probs, k=1, dim=-1)

          # If an EOS token is provided and predicted, stop generation
          if eos_token_id is not None and idx_next == eos_token_id:
              break

          # append sampled index to the running sequence and continue
          idx = torch.cat((idx, idx_next), dim=1)
          attn_times.append(attn_time)

      return idx, sum(attn_times)/len(attn_times)

# Training the data pipeline

import time
from collections import defaultdict

import torch
from torch.utils.data.dataloader import DataLoader


from tokenizers import Tokenizer, models, trainers, pre_tokenizers

def train_bpe_tokenizer(texts, vocab_size=8000, save_path="tokenizer.json"):
    tokenizer = Tokenizer(models.BPE())

    tokenizer.pre_tokenizer = pre_tokenizers.Whitespace()

    trainer = trainers.BpeTrainer(
        vocab_size=vocab_size,
        special_tokens=["<PAD>", "<BOS>", "<EOS>", "<SCHEMA>", "<QUESTION>", "<SQL>"]
    )

    tokenizer.train_from_iterator(texts, trainer)
    tokenizer.save(save_path)

    return tokenizer # Changed to return tokenizer, not tokenize


class Trainer:

    @staticmethod
    def get_default_config():
        C = CfgNode()
        # device to train on
        C.device = 'auto'
        # dataloder parameters
        C.num_workers = 2
        # optimizer parameters
        C.max_iters = 6000
        C.batch_size = 2
        C.learning_rate = 2e-5
        C.betas = (0.9, 0.95)
        C.weight_decay = 0.1 # only applied on matmul weights
        C.grad_norm_clip = 1.0
        return C

    def __init__(self, config, model, train_dataset):
        self.config = config
        self.model = model
        self.optimizer = None
        self.train_dataset = train_dataset
        self.callbacks = defaultdict(list)

        # determine the device we'll train on
        if config.device == 'auto':
            self.device = 'cuda' if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else 'cpu'
        else:
            self.device = config.device
        self.model = self.model.to(self.device)
        print("running on device", self.device)

        # variables that will be assigned to trainer class later for logging and etc
        self.iter_num = 0
        self.iter_time = 0.0
        self.iter_dt = 0.0

    def add_callback(self, onevent: str, callback):
        self.callbacks[onevent].append(callback)

    def set_callback(self, onevent: str, callback):
        self.callbacks[onevent] = [callback]

    def trigger_callbacks(self, onevent: str):
        for callback in self.callbacks.get(onevent, []):
            callback(self)

    def run(self):
        model, config = self.model, self.config

        # setup the optimizer
        self.optimizer = model.configure_optimizers(config)

        # setup the dataloder
        train_loader = DataLoader(
            self.train_dataset,
            sampler=torch.utils.data.RandomSampler(self.train_dataset, replacement=True, num_samples=int(1e10)),
            shuffle=False,
            pin_memory=True,
            batch_size=config.batch_size,
            num_workers=config.num_workers,
        )

        model.train()
        self.iter_num = 0
        self.iter_time = time.time()
        data_iter = iter(train_loader)
        while True:

            # fetch the next batch (x, y) and re-init iterator if needed
            try:
                batch = next(data_iter)
            except StopIteration:
                data_iter = iter(train_loader)
                batch = next(data_iter)
            batch = [t.to(self.device) for t in batch]
            x, y = batch # Unpack batch

            # forward the model
            logits, self.loss, self.attn_times, self.memory_consumed = model(x, y) # Pass x and y

            # backprop and update the parameters
            model.zero_grad(set_to_none=True)
            self.loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), config.grad_norm_clip)
            self.optimizer.step()

            self.trigger_callbacks('on_batch_end')
            self.iter_num += 1
            tnow = time.time()
            self.iter_dt = tnow - self.iter_time
            #self.iter_time = tnow

            # termination conditions
            if config.max_iters is not None and self.iter_num >= config.max_iters:
                break

import os
import sys
import json

import torch
from torch.utils.data import Dataset
from torch.utils.data.dataloader import DataLoader
import pandas as pd
import tokenizers

import pickle
# from __main__ import CfgNode, set_seed, setup_logging, GPT, Trainer # Removed this line
# -----------------------------------------------------------------------------

def get_config():

    C = CfgNode()

    # system
    C.system = CfgNode()
    C.system.seed = 3407
    C.system.work_dir = './out/chargpt'

    # data
    C.data = CharDataset.get_default_config()
    C.data.block_size = 128 # Explicitly set block_size to ensure it's 128
    C.data.input_column = 'text_query' # Override default
    C.data.output_column = 'sql_command' # Override default
    C.data.tokenizer = "bpe" # Set tokenizer to bpe
    C.data.tokenizer_path = '/content/bpe_tokenizer.json' # Path for BPE tokenizer - changed to /content/ for consistency with existing files
    C.data.bpe_vocab_size = 5000 # Vocab size for BPE

    # model
    C.model = GPT.get_default_config()
    #gpt-mini settings
    C.model.n_layer=6
    C.model.n_query_head=6
    C.model.n_kv_head=6
    C.model.n_embd=192
    C.model.n_head=C.model.n_query_head # Fix: Set n_head to n_query_head
    C.model.rope = False # toggle True or False to turn rope on and off respectively

    # trainer
    C.trainer = Trainer.get_default_config()
    C.trainer.learning_rate = 5e-4 # the model we're using is so small that we can go a bit faster

    return C

# -----------------------------------------------------------------------------

class CharDataset(Dataset):
    """
    Emits batches of characters/tokens from a CSV file, combining input and output columns.
    Supports both character-level and BPE tokenization.
    """

    @staticmethod
    def get_default_config():
        C = CfgNode()
        C.block_size = 128
        C.tokenizer="default" # default or bpe
        C.tokenizer_path = None # Path to save/load BPE tokenizer
        C.bpe_vocab_size = 5000 # Vocab size for BPE training
        C.file_path = '/content/sql_dataset.csv' # Path to the CSV file
        C.input_column = 'text_query' # Name of the column containing input text
        C.output_column = 'sql_command' # Name of the column containing output text
        C.delimiter = ' <SEP> ' # Delimiter to separate input and output in the training text
        C.eos_token = '<EOS>' # End-of-sequence token
        C.pad_token = '<PAD>' # Padding token
        C.unk_token = '<UNK>' # Unknown token
        C.bos_token = '<BOS>' # Beginning-of-sequence token
        return C

    def __init__(self, config, data=None):
        self.config = config

        df = pd.read_csv(config.file_path, engine='python', on_bad_lines='warn')
        all_combined_texts = [] # List to hold all combined strings for tokenizer training
        for _, row in df.iterrows():
            input_text = row[config.input_column]
            output_text = row[config.output_column]
            all_combined_texts.append(f"{input_text}{config.delimiter}{output_text}{config.eos_token}")

        raw_text_for_tokenizer_training = ' '.join(all_combined_texts[:20000]) # Use all data for tokenizer training

        if config.tokenizer == "bpe":
            tokenizer_file = config.tokenizer_path
            # Ensure delimiter is also a special token for proper tokenization and sep_id identification
            special_tokens = [config.eos_token, config.pad_token, config.unk_token, config.bos_token, config.delimiter.strip()]

            if not os.path.exists(tokenizer_file):
                print(f"Training new BPE tokenizer and saving to {tokenizer_file}...")
                bpe_tokenizer = tokenizers.ByteLevelBPETokenizer()
                bpe_tokenizer.train_from_iterator(
                    [raw_text_for_tokenizer_training],
                    vocab_size=config.bpe_vocab_size,
                    min_frequency=2,
                    special_tokens=special_tokens
                )
                os.makedirs(os.path.dirname(tokenizer_file), exist_ok=True)
                bpe_tokenizer.save(tokenizer_file)
                print("BPE tokenizer trained and saved.")
            else:
                print(f"Loading BPE tokenizer from {tokenizer_file}...")
                bpe_tokenizer = tokenizers.Tokenizer.from_file(tokenizer_file)

            self.bpe_tokenizer = bpe_tokenizer
            self.vocab_size = bpe_tokenizer.get_vocab_size()
            self.stoi = {token: bpe_tokenizer.token_to_id(token) for token in bpe_tokenizer.get_vocab()} # Mapping for convenience
            self.itos = {id: token for token, id in self.stoi.items() if id is not None} # Mapping for convenience

            # Now, process each combined text into token IDs for the dataset examples
            self.data = [] # This will now be a list of lists (tokenized examples)
            for combined_text in all_combined_texts:
                self.data.append(self.bpe_tokenizer.encode(combined_text).ids)

            print('Dataset has %d examples. Total tokens after individual tokenization: %d unique (BPE).' % (len(self.data), self.vocab_size))

        else: # Character-level tokenization - similar logic needed
            chars = sorted(list(set(raw_text_for_tokenizer_training)))
            for token in [config.eos_token, config.pad_token, config.unk_token, config.bos_token, config.delimiter.strip()]:
                if token not in chars:
                    chars.append(token)
            chars = sorted(chars)

            self.stoi = { ch:i for i,ch in enumerate(chars) }
            self.itos = { i:ch for i,ch in enumerate(chars) }
            self.vocab_size = vocab_size = len(chars)

            self.data = []
            for combined_text in all_combined_texts:
                self.data.append([self.stoi[s] for s in combined_text if s in self.stoi])

            print('Dataset has %d examples. Total characters after individual tokenization: %d unique (Char-level).' % (len(self.data), self.vocab_size))

    def get_vocab_size(self):
        return self.vocab_size

    def get_block_size(self):
        return self.config.block_size

    def get_eos_token_id(self):
        if self.config.tokenizer == "bpe" and hasattr(self, 'bpe_tokenizer') and self.bpe_tokenizer:
            return self.bpe_tokenizer.token_to_id(self.config.eos_token)
        else:
            return self.stoi.get(self.config.eos_token)

    def get_bos_token_id(self):
        if self.config.tokenizer == "bpe" and hasattr(self, 'bpe_tokenizer') and self.bpe_tokenizer:
            return self.bpe_tokenizer.token_to_id(self.config.bos_token)
        else:
            return self.stoi.get(self.config.bos_token)

    def get_pad_token_id(self):
        if self.config.tokenizer == "bpe" and hasattr(self, 'bpe_tokenizer') and self.bpe_tokenizer:
            return self.bpe_tokenizer.token_to_id(self.config.pad_token)
        else:
            return self.stoi.get(self.config.pad_token)


    def __len__(self):
        return len(self.data) # Number of examples in the dataset

    def __getitem__(self, idx):
      # Retrieve one tokenized example (input + delimiter + output + eos)
      full_tokens = self.data[idx]

      # Truncate or pad to block_size + 1 (for x and y)
      block_size = self.config.block_size
      target_length = block_size + 1

      tokens_to_process = full_tokens
      if len(tokens_to_process) < target_length:
          pad_token_id = self.get_pad_token_id()
          if pad_token_id is None:
              raise ValueError(f"PAD token '{self.config.pad_token}' not found or configured for padding in the tokenizer vocabulary.")
          # Pad at the end
          tokens = tokens_to_process + [pad_token_id] * (target_length - len(tokens_to_process))
      else:
          # Truncate from the end to fit block_size + 1
          tokens = tokens_to_process[:target_length]

      x = torch.tensor(tokens[:-1], dtype=torch.long)
      y = torch.tensor(tokens[1:], dtype=torch.long)

      # We no longer need to return loss_mask
      return x, y

    # Add decode helper for BPE tokenization
    def decode(self, token_ids):
        if self.config.tokenizer == "bpe" and hasattr(self, 'bpe_tokenizer') and self.bpe_tokenizer:
            return self.bpe_tokenizer.decode(token_ids)
        else:
            # Fallback to character-level decoding if not BPE or tokenizer not present
            return ''.join([self.itos[int(i)] for i in token_ids if int(i) in self.itos])

# -----------------------------------------------------------------------------

# This code block is moved out of the `if __name__ == '__main__':` guard
# to ensure `config`, `train_dataset`, `model`, and `trainer` are always defined
# when this cell is executed in a notebook environment.

config = get_config()
# Filter sys.argv to only include arguments that start with '--'
filtered_args = [arg for arg in sys.argv[1:] if arg.startswith('--')]
config.merge_from_args(filtered_args)
set_seed(config.system.seed)

# construct the training dataset from CSV
train_dataset = CharDataset(config.data)

# construct the model
config.model.vocab_size = train_dataset.get_vocab_size()
config.model.block_size = train_dataset.get_block_size()
print(config)
model = GPT(config.model)

if config.model.pretrained_folder!=None:
    assert os.path.normpath(os.path.abspath(config.model.pretrained_folder)) != os.path.normpath(os.path.abspath(config.system.work_dir)), "pretrained folder cannot be same as current folder. Change the folder name of your pretrained model or current directory using flags"
    model.load_pretrained(config.model.pretrained_folder)

setup_logging(config)

# construct the trainer object
trainer = Trainer(config.trainer, model, train_dataset)

train_losses = []
attn_times = []
attn_mem = []

# iteration callback
def batch_end_callback(trainer):
    if trainer.iter_num % 1 == 0:
        train_losses.append(trainer.loss.item())
        attn_times.append(trainer.attn_times*1000)
        if trainer.device=="cuda":
            print(f"iter_dt {trainer.iter_dt:.2f}s; iter {trainer.iter_num}: train loss {trainer.loss.item():.5f};attn_times {trainer.attn_times*1000:.2f}ms;mem_consumed {trainer.memory_consumed/(1024*1024):.2f}MB")
            attn_mem.append(trainer.memory_consumed/(1024*1024))
        else:
            print(f"iter_dt {trainer.iter_dt:.2f}s; iter {trainer.iter_num}: train loss {trainer.loss.item():.5f};attn_times {trainer.attn_times*1000:.2f}ms;mem_consumed - not available on CPU")

    if (trainer.iter_num + 1) % 200 == 0:
        # evaluate both the train and test score
        model.eval()
        with torch.no_grad():
            # sample from the model...
            # Context for generation should match the training input format
            context = f"What is the capital of France?{train_dataset.config.delimiter}"

            if train_dataset.config.tokenizer == "bpe" and hasattr(train_dataset, 'bpe_tokenizer'):
                # Use BPE tokenizer for encoding
                encoded_context = train_dataset.bpe_tokenizer.encode(context).ids
            else:
                # Fallback to character-level if BPE not used or not initialized
                encoded_context = [train_dataset.stoi[s] for s in context if s in train_dataset.stoi]

            if not encoded_context:
                print("Warning: Context string contains no known tokens. Skipping generation.")
                # Fallback or handle as appropriate, e.g., create a default context using BOS token
                # Ensure BOS token ID is valid, or fallback to a dummy value if not available
                bos_token_id = train_dataset.get_bos_token_id()
                encoded_context = [bos_token_id if bos_token_id is not None else 0] # Use 0 as a default if BOS token ID is not found

            x = torch.tensor(encoded_context, dtype=torch.long)[None,...].to(trainer.device)
            # Ensure eos_token_id is passed correctly
            eos_id_for_generation = train_dataset.get_eos_token_id()
            if eos_id_for_generation is None:
                print("Warning: EOS token ID not found for generation. Generation might not stop as expected.")

            y, attn_time = model.generate(x, 500, temperature=1.0, do_sample=True, top_k=10, eos_token_id=eos_id_for_generation)
            y = y[0]

            completion_tokens = y.tolist()

            # --- Handle EOS token for display ---
            # Find the index of the EOS token if present
            if eos_id_for_generation is not None:
                try:
                    eos_idx = completion_tokens.index(eos_id_for_generation)
                    completion_tokens = completion_tokens[:eos_idx] # Truncate at EOS token
                except ValueError:
                    # EOS token not found, use the full generated text
                    pass

            # Use the decode helper method
            completion = train_dataset.decode(completion_tokens)

            print(completion)
            print(f"Attention computation took {attn_time*1000:.2f}ms to run for {config.data.block_size} seq length")
        # save the latest model
        print("saving model")
        ckpt_path = os.path.join(config.system.work_dir, "model.pt")
        torch.save(model.state_dict(), ckpt_path)
        print("saving loss and attention logs")
        with open(os.path.join(config.system.work_dir, 'train_losses.json'), 'w') as f:
            json.dump(train_losses, f, ensure_ascii=False, indent=4)
        with open(os.path.join(config.system.work_dir, 'attention_computation_time.json'), 'w') as f:
            json.dump(attn_times, f, ensure_ascii=False, indent=4)
        with open(os.path.join(config.system.work_dir, 'attention_computation_memory.json'), 'w') as f:
            json.dump(attn_mem, f, ensure_ascii=False, indent=4)
        # revert model to training mode
        model.train()

trainer.set_callback('on_batch_end', batch_end_callback)

# run the optimization
trainer.run()

print(f"The model's context length (block_size) is: {train_dataset.get_block_size()}")

# Put the model in evaluation mode
model.eval()

# Input question
input_question = """Name the metrical equivalence for linha ### Input: CREATE TABLE table_28772 (
 "Portuguese name" text,
 "English name" text,
 "Subdivides in" text,
 "Equivalence in Varas" text,
 "Metrical equivalence" text
)"""

# ✅ Build structured prompt (VERY important)
context_for_generation = f"{input_question} {train_dataset.config.delimiter}"
print(f"Generation prompt: {context_for_generation}")

# ✅ Encode using BPE tokenizer
encoded_context = train_dataset.bpe_tokenizer.encode(context_for_generation).ids

# Convert to tensor
x_input = torch.tensor(encoded_context, dtype=torch.long)[None, ...].to(trainer.device)

# ✅ Generate
y_generated, _ = model.generate(
    x_input,
    max_new_tokens=300,
    temperature=0.1,
    do_sample=True,
    top_k=5,
    eos_token_id=train_dataset.get_eos_token_id()
)

# ✅ Convert tokens to list
completion_tokens = y_generated[0].tolist()

# ✅ Handle EOS token
eos_id = train_dataset.get_eos_token_id()
if eos_id is not None and eos_id in completion_tokens:
    eos_idx = completion_tokens.index(eos_id)
    completion_tokens = completion_tokens[:eos_idx]

# ✅ Decode using tokenizer (IMPORTANT)
completion = train_dataset.decode(completion_tokens)

print("\nGenerated text: \n")
print(completion)
print("\n\n")

# Revert model to training mode if needed
model.train()

from google.colab import files
import os

# Ensure the work directory path is correctly defined
# Assuming config.system.work_dir holds the path to where model.pt is saved
# If you rerun the training, the model.pt will be updated in this directory.
work_dir = './out/chargpt'
model_path = os.path.join(work_dir, 'model.pt')

if os.path.exists(model_path):
    files.download(model_path)
    print(f"'{model_path}' downloaded successfully.")
else:
    print(f"Error: '{model_path}' not found. Please ensure the model has been trained and saved.")